import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request) {
  try {
    const { email, contractType, riskScore, result } = await request.json();

    if (!email || !result) {
      return Response.json({ error: "Email and result are required." }, { status: 400 });
    }

    const getRiskColor = (score) => {
      if (score >= 7) return "#ef4444";
      if (score >= 4) return "#f97316";
      return "#10b981";
    };

    const getRiskLabel = (score) => {
      if (score >= 7) return "HIGH RISK";
      if (score >= 4) return "MEDIUM RISK";
      return "LOW RISK";
    };

    const parseSection = (text, heading) => {
      const regex = new RegExp(`## ${heading}([\\s\\S]*?)(?=## |$)`);
      const match = text.match(regex);
      return match ? match[1].trim() : "Not found in document.";
    };

    const tldr = parseSection(result, "TL;DR");
    const risks = parseSection(result, "RISKS IDENTIFIED");
    const suggestions = parseSection(result, "SUGGESTIONS");

    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>LegalLens Contract Analysis Report</title>
</head>
<body style="margin:0;padding:0;background:#0a0f1e;font-family:'Segoe UI',Arial,sans-serif;">

  <div style="max-width:600px;margin:0 auto;padding:32px 16px;">

    <!-- Header -->
    <div style="text-align:center;margin-bottom:32px;">
      <div style="display:inline-block;background:linear-gradient(135deg,#3b82f6,#6366f1);border-radius:16px;padding:16px 24px;margin-bottom:16px;">
        <span style="font-size:32px;">⚖️</span>
      </div>
      <h1 style="color:#f9fafb;font-size:28px;font-weight:900;margin:0 0 8px;letter-spacing:-1px;">LegalLens</h1>
      <p style="color:#6b7280;font-size:14px;margin:0;">Your Contract Analysis Report</p>
    </div>

    <!-- Risk Score Card -->
    <div style="background:#111827;border:1px solid #1f2937;border-radius:16px;padding:24px;margin-bottom:20px;text-align:center;">
      <p style="color:#9ca3af;font-size:12px;font-weight:600;letter-spacing:1px;margin:0 0 8px;">OVERALL RISK SCORE</p>
      <div style="font-size:48px;font-weight:900;color:${getRiskColor(riskScore)};margin:0 0 8px;">${riskScore}/10</div>
      <div style="display:inline-block;background:${getRiskColor(riskScore)}22;border:1px solid ${getRiskColor(riskScore)}44;border-radius:20px;padding:4px 16px;">
        <span style="color:${getRiskColor(riskScore)};font-size:13px;font-weight:700;">${getRiskLabel(riskScore)}</span>
      </div>
      <p style="color:#6b7280;font-size:13px;margin:12px 0 0;">Contract Type: <strong style="color:#f9fafb;">${contractType || "Unknown"}</strong></p>
    </div>

    <!-- TL;DR -->
    <div style="background:#111827;border:1px solid #1f2937;border-left:3px solid #3b82f6;border-radius:12px;padding:20px;margin-bottom:16px;">
      <h2 style="color:#f9fafb;font-size:16px;font-weight:700;margin:0 0 12px;">📋 Quick Summary (TL;DR)</h2>
      <p style="color:#d1d5db;font-size:14px;line-height:1.7;margin:0;white-space:pre-wrap;">${tldr}</p>
    </div>

    <!-- Risks -->
    <div style="background:#111827;border:1px solid #1f2937;border-left:3px solid #ef4444;border-radius:12px;padding:20px;margin-bottom:16px;">
      <h2 style="color:#f9fafb;font-size:16px;font-weight:700;margin:0 0 12px;">⚠️ Risks Identified</h2>
      <p style="color:#d1d5db;font-size:14px;line-height:1.7;margin:0;white-space:pre-wrap;">${risks}</p>
    </div>

    <!-- Suggestions -->
    <div style="background:#111827;border:1px solid #1f2937;border-left:3px solid #10b981;border-radius:12px;padding:20px;margin-bottom:32px;">
      <h2 style="color:#f9fafb;font-size:16px;font-weight:700;margin:0 0 12px;">💡 Suggestions</h2>
      <p style="color:#d1d5db;font-size:14px;line-height:1.7;margin:0;white-space:pre-wrap;">${suggestions}</p>
    </div>

    <!-- Footer -->
    <div style="text-align:center;padding-top:24px;border-top:1px solid #1f2937;">
      <p style="color:#4b5563;font-size:12px;margin:0 0 8px;">Generated by LegalLens · AI Contract Analyzer</p>
      <p style="color:#374151;font-size:11px;margin:0;">⚠️ This is an AI-generated analysis. Always consult a real lawyer for important decisions.</p>
    </div>

  </div>
</body>
</html>
    `;

    const { data, error } = await resend.emails.send({
      from: "LegalLens <onboarding@resend.dev>",
      to: email,
      subject: `Your LegalLens Report — ${contractType || "Contract"} · Risk: ${getRiskLabel(riskScore)}`,
      html: htmlContent,
    });

    if (error) {
      return Response.json({ error: error.message }, { status: 400 });
    }

    return Response.json({ success: true, id: data.id });

  } catch (err) {
    return Response.json({ error: "Failed to send email. Please try again." }, { status: 500 });
  }
}